name: filmoteka
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.17
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  file_picker: ^4.6.1
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  http: ^0.13.4
  json_annotation: ^4.5.0
  path: ^1.8.1
  path_provider: ^2.0.8
  provider: ^6.0.2
  shared_preferences: ^2.0.12

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/plug.jpg
    - assets/main.jpg
    - .env

